### ISSUE TITLE
Cannot run example due to type errors

### ISSUE THREAD

**Issue by PlantPorridge** [neuronetio/angular-gantt-schedule-timeline-calendar-example#1]
1. Clone repo
2. run 'npm i'
3. run 'npm start'
4. The build fails with the following error:

![image](https://user-images.githubusercontent.com/28366926/101191973-4ce18b80-3652-11eb-89a7-a817c44e1e49.png)

**Comment by neuronetio** [comment]
fixed in `3.6.5`
